target:
	cd /schemas 

create:
	sqlite3 ../db/character.db < character.sql
	sqlite3 ../db/feats.db < feats.sql
	sqlite3 ../db/items.db < items.sql
	sqlite3 ../db/race.db < race.sql
	sqlite3 ../db/spells.db < spells.sql
	sqlite3 ../db/users.db < users.sql